# Generated by Django 6.0.5 on 2026-05-11 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("ROLE_CHANGE", "Role change"),
                            ("DATA_REDUCTION", "Data reduction"),
                            ("IMPORT", "Import"),
                            ("STAGE_TRANSITION", "Stage transition"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Timestamp"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=255, verbose_name="Object"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit entry",
                "verbose_name_plural": "Audit entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
