# Generated by Django 6.0.5 on 2026-05-11 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name_de", models.CharField(max_length=100, verbose_name="Name (DE)")),
                ("name_en", models.CharField(max_length=100, verbose_name="Name (EN)")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Order"
                    ),
                ),
                ("is_final", models.BooleanField(default=False, verbose_name="Is final state")),
                ("is_archive", models.BooleanField(default=False, verbose_name="Is archive stage")),
            ],
            options={
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=255, verbose_name="Company name"),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, verbose_name="Domain"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, verbose_name="Location")),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Industry / Tech focus"
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Product / Technology"
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=100, verbose_name="Company size")),
                ("investors", models.TextField(blank=True, verbose_name="Investors / Funding")),
                ("source", models.CharField(blank=True, max_length=255, verbose_name="Source")),
                ("rejection_reason", models.TextField(blank=True, verbose_name="Rejection reason")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_companies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="companies",
                        to="leads.stage",
                        verbose_name="Current stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "salutation",
                    models.CharField(blank=True, max_length=50, verbose_name="Salutation"),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, verbose_name="Last name"),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Full name"),
                ),
                ("position", models.CharField(blank=True, max_length=255, verbose_name="Position")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=100, verbose_name="Phone")),
                ("linkedin_url", models.URLField(blank=True, verbose_name="LinkedIn URL")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="leads.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="PRBriefing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reality_check", models.TextField(blank=True, verbose_name="Reality check")),
                ("ai_perception", models.TextField(blank=True, verbose_name="AI perception")),
                (
                    "ai_profile_clarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("H", "High / Hoch"),
                            ("M", "Medium / Mittel"),
                            ("G", "Low / Gering"),
                        ],
                        max_length=1,
                        verbose_name="AI profile clarity",
                    ),
                ),
                ("media_hook", models.TextField(blank=True, verbose_name="Media hook")),
                (
                    "value_for_decision_makers",
                    models.TextField(blank=True, verbose_name="Value for decision makers"),
                ),
                (
                    "communication_goal",
                    models.TextField(blank=True, verbose_name="Communication goal"),
                ),
                ("trigger_event", models.TextField(blank=True, verbose_name="Trigger event")),
                (
                    "trigger_type",
                    models.CharField(blank=True, max_length=255, verbose_name="Trigger type"),
                ),
                (
                    "communication_gap",
                    models.TextField(blank=True, verbose_name="Communication gap"),
                ),
                (
                    "innovation_seriousness",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Innovative / Serious"
                    ),
                ),
                (
                    "story_potential",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="PR story potential (1–5)",
                    ),
                ),
                (
                    "fit_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Fit score (1–5)",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        max_length=1,
                        verbose_name="Priority",
                    ),
                ),
                ("press_news", models.TextField(blank=True, verbose_name="Press / News")),
                ("next_step", models.TextField(blank=True, verbose_name="Next step")),
                (
                    "last_contact",
                    models.DateField(blank=True, null=True, verbose_name="Last contact"),
                ),
                (
                    "research_date",
                    models.DateField(blank=True, null=True, verbose_name="Research date"),
                ),
                (
                    "last_update",
                    models.DateField(blank=True, null=True, verbose_name="Last update"),
                ),
                (
                    "currency_check",
                    models.TextField(blank=True, verbose_name="Currency check (Aktualität)"),
                ),
                ("update_needed", models.BooleanField(default=False, verbose_name="Update needed")),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prbriefing",
                        to="leads.company",
                        verbose_name="Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "PR Briefing",
                "verbose_name_plural": "PR Briefings",
            },
        ),
        migrations.CreateModel(
            name="StageTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transitioned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Transitioned at"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Comment")),
                (
                    "by_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_transitions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="By user",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_transitions",
                        to="leads.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "from_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leads.stage",
                        verbose_name="From stage",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="leads.stage",
                        verbose_name="To stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage transition",
                "verbose_name_plural": "Stage transitions",
                "ordering": ["-transitioned_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                fields=("name", "domain"), name="unique_company_name_domain"
            ),
        ),
    ]
