# Generated by Django 6.0.5 on 2026-05-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_default_stages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prbriefing",
            name="fit_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
                verbose_name="Fit score (1-5)",
            ),
        ),
        migrations.AlterField(
            model_name="prbriefing",
            name="story_potential",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
                verbose_name="PR story potential (1-5)",
            ),
        ),
    ]
