# Generated by Django 6.0.5 on 2026-05-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0003_alter_prbriefing_fit_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="b2b_technology",
            field=models.TextField(blank=True, verbose_name="B2B Technology"),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=255, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Country"),
        ),
        migrations.AddField(
            model_name="company",
            name="postcode",
            field=models.CharField(blank=True, max_length=20, verbose_name="Postcode"),
        ),
        migrations.AddField(
            model_name="company",
            name="street",
            field=models.CharField(blank=True, max_length=255, verbose_name="Street"),
        ),
    ]
