# Generated by Django 6.0.5 on 2026-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0004_company_b2b_technology_company_city_company_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="LinkedIn URL"),
        ),
    ]
