# Generated by Django 6.0.5 on 2026-05-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0005_contact_linkedin_url_max500"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="product",
            field=models.TextField(blank=True, verbose_name="Product / Technology"),
        ),
    ]
