# Generated by Django 6.0.5 on 2026-05-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0006_company_product_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prbriefing",
            name="innovation_seriousness",
            field=models.TextField(blank=True, verbose_name="Innovative / Serious"),
        ),
        migrations.AlterField(
            model_name="prbriefing",
            name="trigger_type",
            field=models.TextField(blank=True, verbose_name="Trigger type"),
        ),
    ]
