# Generated by Django 6.0.5 on 2026-05-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0007_prbriefing_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.TextField(blank=True, verbose_name="Phone"),
        ),
    ]
