# Generated by Django 6.0.5 on 2026-05-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0008_contact_phone_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="size",
            field=models.TextField(blank=True, verbose_name="Company size"),
        ),
    ]
