# Generated by Django 6.0.5 on 2026-05-11 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("LETTER", "Letter / Brief"),
                            ("PHONE", "Phone / Telefon"),
                            ("LINKEDIN", "LinkedIn"),
                            ("EMAIL", "Email / E-Mail"),
                            ("OTHER", "Other / Sonstige"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Channel",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("OUT", "Outbound"), ("IN", "Inbound")],
                        max_length=3,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_reached", "Not reached / Nicht erreicht"),
                            ("callback", "Callback agreed / Rückruf vereinbart"),
                            ("voicemail", "Voicemail / Mailbox"),
                            ("interested", "Interested / Interesse"),
                            ("not_interested", "Not interested / Kein Interesse"),
                            ("meeting", "Meeting scheduled / Termin vereinbart"),
                            ("sent", "Sent / Versandt"),
                            ("connected", "Connected / Verbunden"),
                            ("message_sent", "Message sent / Nachricht gesendet"),
                            ("other", "Other / Sonstige"),
                        ],
                        max_length=50,
                        verbose_name="Outcome",
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True, verbose_name="Occurred at")),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Duration (seconds)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="leads.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="leads.contact",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-occurred_at"],
            },
        ),
    ]
