# Generated by Django 6.0.5 on 2026-05-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="subject",
            field=models.CharField(blank=True, max_length=255, verbose_name="Subject"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_reached", "Not reached / Nicht erreicht"),
                    ("callback", "Callback agreed / Rückruf vereinbart"),
                    ("voicemail", "Voicemail / Mailbox"),
                    ("interested", "Interested / Interesse"),
                    ("not_interested", "Not interested / Kein Interesse"),
                    ("meeting", "Meeting scheduled / Termin vereinbart"),
                    ("sent", "Sent / Versandt"),
                    ("connected", "Connected / Verbunden"),
                    ("message_sent", "Message sent / Nachricht gesendet"),
                    ("comment", "Comment / Kommentar"),
                    ("reaction", "Reaction / Reaktion"),
                    ("other", "Other / Sonstige"),
                ],
                max_length=50,
                verbose_name="Outcome",
            ),
        ),
    ]
