# Generated by Django 6.0.5 on 2026-05-11 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_filename",
                    models.CharField(max_length=255, verbose_name="Source filename"),
                ),
                (
                    "performed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Performed at"),
                ),
                (
                    "rows_created",
                    models.PositiveIntegerField(default=0, verbose_name="Rows created"),
                ),
                (
                    "rows_updated",
                    models.PositiveIntegerField(default=0, verbose_name="Rows updated"),
                ),
                (
                    "rows_skipped",
                    models.PositiveIntegerField(default=0, verbose_name="Rows skipped"),
                ),
                ("errors_json", models.JSONField(default=list, verbose_name="Errors")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import batch",
                "verbose_name_plural": "Import batches",
                "ordering": ["-performed_at"],
            },
        ),
    ]
